var SHRINES = [
{
"n": "坐摩神社",
"a": "大阪市中央区久太郎町4丁目渡辺3号",
"s": "式内社（大社）",
"r": "",
"k": "",
"d": "",
"c": "",
"m": "坐摩大神（生井神・福井神・綱長井神・阿須波神・波比岐神）",
"ne": "Ikasuri Shrine",
"ae": "Watanabe 3, Kyutaromachi 4-chome, Chuo-ku, Osaka",
"se": "Shikinai-sha (Engishiki-listed) · Grand Shrine",
"me": "Ikasuri-no-Okami (Ikui, Fukui, Tsunagai, Asuha and Hahiki deities)"
},
{
"n": "坐摩神社行宮",
"a": "大阪市中央区石町（番地は未確認）",
"s": "",
"r": "坐摩神社の行宮（御旅所）",
"k": "史跡（窪津王子跡）",
"d": "",
"c": "",
"m": "",
"ne": "Ikasuri Shrine Angu (temporary shrine)",
"ae": "Ishimachi, Chuo-ku, Osaka (street number unconfirmed)",
"re": "Angu / Otabisho (temporary shrine) of {P}",
"ke": "Historic site (site of Kubotsu Oji)"
},
{
"n": "高津宮",
"a": "大阪市中央区高津1-1-29",
"s": "",
"r": "",
"k": "",
"d": "",
"c": "866年（貞観8年）",
"m": "",
"ne": "Kozu-gu Shrine",
"ae": "1-1-29 Kozu, Chuo-ku, Osaka",
"ce": "866 (Jogan 8)"
},
{
"n": "比売許曽神社（高津宮の境内社）",
"a": "大阪市中央区高津1-1-29",
"s": "式内社（論社）",
"r": "高津宮の境内社",
"k": "",
"d": "",
"c": "",
"m": "",
"ne": "Himekoso Shrine (within Kozu-gu Shrine)",
"ae": "1-1-29 Kozu, Chuo-ku, Osaka",
"se": "Shikinai-sha (candidate site, ronsha)",
"re": "Shrine within the precincts of {P}"
},
{
"n": "少彦名神社",
"a": "大阪市中央区道修町2-1-8",
"s": "",
"r": "",
"k": "",
"d": "",
"c": "1780年（安永9年）",
"m": "",
"ne": "Sukunahikona Shrine",
"ae": "2-1-8 Doshomachi, Chuo-ku, Osaka",
"ce": "1780 (Anei 9)"
},
{
"n": "玉造稲荷神社",
"a": "大阪市中央区玉造2-3-8",
"s": "",
"r": "",
"k": "",
"d": "",
"c": "",
"m": "",
"ne": "Tamatsukuri Inari Shrine",
"ae": "2-3-8 Tamatsukuri, Chuo-ku, Osaka"
},
{
"n": "豊國神社",
"a": "大阪市中央区大阪城2-1",
"s": "",
"r": "",
"k": "",
"d": "",
"c": "",
"m": "",
"ne": "Toyokuni Shrine",
"ae": "2-1 Osakajo, Chuo-ku, Osaka"
},
{
"n": "御津宮",
"a": "大阪市中央区西心斎橋2-10-7",
"s": "",
"r": "",
"k": "",
"d": "",
"c": "",
"m": "",
"ne": "Mitsu-gu Shrine",
"ae": "2-10-7 Nishi-Shinsaibashi, Chuo-ku, Osaka"
},
{
"n": "鵲森宮",
"a": "大阪市中央区森ノ宮中央1-14-4",
"s": "",
"r": "",
"k": "",
"d": "",
"c": "",
"m": "",
"ne": "Kasasagimori-no-miya Shrine",
"ae": "1-14-4 Morinomiya-Chuo, Chuo-ku, Osaka"
},
{
"n": "御霊神社",
"a": "大阪市中央区淡路町4-4-3",
"s": "国史見在社",
"r": "",
"k": "",
"d": "",
"c": "",
"m": "",
"ne": "Goryo Shrine",
"ae": "4-4-3 Awajimachi, Chuo-ku, Osaka",
"se": "Kokushi-kenzaisha (named in the Six National Histories)"
},
{
"n": "御霊神社行宮",
"a": "大阪市（所在地は未確認）",
"s": "",
"r": "御霊神社の行宮（御旅所）",
"k": "",
"d": "",
"c": "",
"m": "",
"ne": "Goryo Shrine Angu (temporary shrine)",
"ae": "Osaka (location unconfirmed)",
"re": "Angu / Otabisho (temporary shrine) of {P}"
},
{
"n": "難波神社",
"a": "大阪市中央区博労町4-1-3",
"s": "",
"r": "",
"k": "",
"d": "",
"c": "",
"m": "",
"ne": "Namba Shrine",
"ae": "4-1-3 Bakurocho, Chuo-ku, Osaka"
},
{
"n": "茨住吉神社",
"a": "大阪市西区九条1-1-17",
"s": "",
"r": "",
"k": "",
"d": "",
"c": "",
"m": "",
"ne": "Ibara Sumiyoshi Shrine",
"ae": "1-1-17 Kujo, Nishi-ku, Osaka"
},
{
"n": "土佐稲荷神社",
"a": "大阪市西区北堀江4-9-7",
"s": "",
"r": "",
"k": "",
"d": "",
"c": "",
"m": "",
"ne": "Tosa Inari Shrine",
"ae": "4-9-7 Kita-Horie, Nishi-ku, Osaka"
},
{
"n": "楠永神社",
"a": "大阪市西区靱本町2-1",
"s": "",
"r": "",
"k": "",
"d": "",
"c": "",
"m": "楠永大神・楠玉大神",
"ne": "Kusunaga Shrine",
"ae": "2-1 Utsubo-Honmachi, Nishi-ku, Osaka",
"me": "Kusunaga-no-Okami and Kusutama-no-Okami"
},
{
"n": "サムハラ神社",
"a": "大阪市西区立売堀2-5-26",
"s": "",
"r": "",
"k": "",
"d": "",
"c": "",
"m": "",
"ne": "Samuhara Shrine",
"ae": "2-5-26 Itachibori, Nishi-ku, Osaka"
},
{
"n": "熊野大神宮",
"a": "大阪市東成区大今里4-16-48",
"s": "",
"r": "",
"k": "",
"d": "",
"c": "",
"m": "",
"ne": "Kumano Dai-jingu Shrine",
"ae": "4-16-48 Oimazato, Higashinari-ku, Osaka"
},
{
"n": "熊野大神宮御旅所",
"a": "大阪市東成区東今里（番地は未確認）",
"s": "",
"r": "熊野大神宮の行宮（御旅所）",
"k": "",
"d": "",
"c": "",
"m": "",
"ne": "Kumano Dai-jingu Otabisho (procession rest site)",
"ae": "Higashi-Imazato, Higashinari-ku, Osaka (street number unconfirmed)",
"re": "Angu / Otabisho (temporary shrine) of {P}"
},
{
"n": "八王子神社",
"a": "大阪市東成区中本4-2-48",
"s": "",
"r": "",
"k": "",
"d": "",
"c": "",
"m": "",
"ne": "Hachioji Shrine",
"ae": "4-2-48 Nakamoto, Higashinari-ku, Osaka"
},
{
"n": "八王子神社御旅所",
"a": "大阪市東成区大今里（番地は未確認）",
"s": "",
"r": "八王子神社の行宮（御旅所）",
"k": "",
"d": "",
"c": "",
"m": "",
"ne": "Hachioji Shrine Otabisho (procession rest site)",
"ae": "Oimazato, Higashinari-ku, Osaka (street number unconfirmed)",
"re": "Angu / Otabisho (temporary shrine) of {P}"
},
{
"n": "比賣許曽神社",
"a": "大阪市東成区東小橋3-8-14",
"s": "式内社（名神大）",
"r": "",
"k": "",
"d": "",
"c": "",
"m": "下照比売命",
"ne": "Himekoso Shrine",
"ae": "3-8-14 Higashi-Obashi, Higashinari-ku, Osaka",
"se": "Shikinai-sha (Engishiki-listed) · Myojin Taisha",
"me": "Shitateruhime-no-Mikoto"
},
{
"n": "産湯稲荷神社",
"a": "大阪市天王寺区小橋町（番地は未確認）",
"s": "式内社（旧社地の伝承）",
"r": "比賣許曽神社の境外摂社",
"k": "",
"d": "",
"c": "",
"m": "",
"ne": "Ubuyu Inari Shrine",
"ae": "Obashicho, Tennoji-ku, Osaka (street number unconfirmed)",
"se": "Shikinai-sha (traditional former site)",
"re": "Off-site subsidiary shrine (Sessha) of {P}"
},
{
"n": "八阪神社",
"a": "大阪市東成区中道4-8-20",
"s": "",
"r": "",
"k": "",
"d": "",
"c": "",
"m": "",
"ne": "Yasaka Shrine",
"ae": "4-8-20 Nakamichi, Higashinari-ku, Osaka"
},
{
"n": "深江稲荷神社",
"a": "大阪市東成区深江南3-16-17",
"s": "",
"r": "",
"k": "",
"d": "",
"c": "",
"m": "",
"ne": "Fukae Inari Shrine",
"ae": "3-16-17 Fukae-Minami, Higashinari-ku, Osaka"
},
{
"n": "三社神社",
"a": "大阪市港区磯路2-18-23",
"s": "",
"r": "",
"k": "",
"d": "",
"c": "",
"m": "",
"ne": "Sansha Shrine",
"ae": "2-18-23 Isoji, Minato-ku, Osaka"
},
{
"n": "三津神社",
"a": "大阪市港区夕凪2-6-11",
"s": "",
"r": "",
"k": "",
"d": "",
"c": "",
"m": "",
"ne": "Mitsu Shrine",
"ae": "2-6-11 Yunagi, Minato-ku, Osaka"
},
{
"n": "三先天満宮",
"a": "大阪市港区三先1-5-40",
"s": "",
"r": "",
"k": "",
"d": "",
"c": "",
"m": "",
"ne": "Misaki Tenmangu Shrine",
"ae": "1-5-40 Misaki, Minato-ku, Osaka"
},
{
"n": "福崎住吉神社",
"a": "大阪市港区福崎1-1-39",
"s": "",
"r": "",
"k": "",
"d": "",
"c": "",
"m": "",
"ne": "Fukuzaki Sumiyoshi Shrine",
"ae": "1-1-39 Fukuzaki, Minato-ku, Osaka"
},
{
"n": "湊屋住吉神社",
"a": "大阪市港区池島2-8-4",
"s": "",
"r": "",
"k": "",
"d": "",
"c": "",
"m": "",
"ne": "Minatoya Sumiyoshi Shrine",
"ae": "2-8-4 Ikejima, Minato-ku, Osaka"
},
{
"n": "産土神社",
"a": "大阪市此花区島屋3-13-28",
"s": "",
"r": "",
"k": "",
"d": "",
"c": "",
"m": "",
"ne": "Ubusuna Shrine",
"ae": "3-13-28 Shimaya, Konohana-ku, Osaka"
},
{
"n": "四貫島住吉神社",
"a": "大阪市此花区梅香3-14-16",
"s": "",
"r": "",
"k": "",
"d": "",
"c": "",
"m": "",
"ne": "Shikanjima Sumiyoshi Shrine",
"ae": "3-14-16 Umeka, Konohana-ku, Osaka"
},
{
"n": "朝日神明社",
"a": "大阪市此花区春日出中1-6-21",
"s": "",
"r": "",
"k": "",
"d": "",
"c": "",
"m": "",
"ne": "Asahi Shinmeisha Shrine",
"ae": "1-6-21 Kasugade-Naka, Konohana-ku, Osaka"
},
{
"n": "鴉宮",
"a": "大阪市此花区伝法2-10-18",
"s": "",
"r": "",
"k": "",
"d": "",
"c": "",
"m": "",
"ne": "Karasu-no-miya Shrine",
"ae": "2-10-18 Denpo, Konohana-ku, Osaka"
},
{
"n": "澪標住吉神社",
"a": "大阪市此花区伝法3-1-6",
"s": "",
"r": "",
"k": "",
"d": "",
"c": "",
"m": "",
"ne": "Miotsukushi Sumiyoshi Shrine",
"ae": "3-1-6 Denpo, Konohana-ku, Osaka"
},
{
"n": "西九条神社",
"a": "大阪市此花区西九条1-4-20",
"s": "",
"r": "",
"k": "",
"d": "",
"c": "",
"m": "",
"ne": "Nishikujo Shrine",
"ae": "1-4-20 Nishikujo, Konohana-ku, Osaka"
},
{
"n": "大阪天満宮",
"a": "大阪市北区天神橋2-1-8",
"s": "",
"r": "",
"k": "",
"d": "",
"c": "949年（天暦3年）",
"m": "菅原道真",
"ne": "Osaka Tenmangu Shrine",
"ae": "2-1-8 Tenjinbashi, Kita-ku, Osaka",
"ce": "949 (Tenryaku 3)",
"me": "Sugawara no Michizane"
},
{
"n": "天満宮行宮",
"a": "大阪市西区千代崎（番地は未確認）",
"s": "",
"r": "大阪天満宮の行宮（所属は要確認）",
"k": "",
"d": "",
"c": "",
"m": "",
"ne": "Tenmangu Angu (temporary shrine)",
"ae": "Chiyozaki, Nishi-ku, Osaka (street number unconfirmed)",
"re": "Angu (temporary shrine) of {P} (affiliation to be confirmed)"
},
{
"n": "堀川戎神社",
"a": "大阪市北区西天満5-4-17",
"s": "",
"r": "",
"k": "",
"d": "",
"c": "",
"m": "",
"ne": "Horikawa Ebisu Shrine",
"ae": "5-4-17 Nishitenma, Kita-ku, Osaka"
},
{
"n": "露天神社",
"a": "大阪市北区曽根崎2-5-4",
"s": "",
"r": "",
"k": "",
"d": "",
"c": "",
"m": "",
"ne": "Tsuyunoten Shrine (Ohatsu Tenjin)",
"ae": "2-5-4 Sonezaki, Kita-ku, Osaka"
},
{
"n": "豊崎神社",
"a": "大阪市北区豊崎6-6-4",
"s": "",
"r": "",
"k": "",
"d": "",
"c": "",
"m": "",
"ne": "Toyosaki Shrine",
"ae": "6-6-4 Toyosaki, Kita-ku, Osaka"
},
{
"n": "綱敷天神社",
"a": "大阪市北区神山町9-11",
"s": "",
"r": "",
"k": "",
"d": "",
"c": "",
"m": "",
"ne": "Tsunashiki Tenjin Shrine",
"ae": "9-11 Kamiyamacho, Kita-ku, Osaka"
},
{
"n": "綱敷天神社御旅所",
"a": "大阪市北区茶屋町（番地は未確認）",
"s": "",
"r": "綱敷天神社の行宮（御旅所）",
"k": "",
"d": "",
"c": "",
"m": "",
"ne": "Tsunashiki Tenjin Shrine Otabisho (procession rest site)",
"ae": "Chayamachi, Kita-ku, Osaka (street number unconfirmed)",
"re": "Angu / Otabisho (temporary shrine) of {P}"
},
{
"n": "長柄八幡宮",
"a": "大阪市北区長柄中3-3-1",
"s": "",
"r": "",
"k": "",
"d": "",
"c": "",
"m": "",
"ne": "Nagara Hachimangu Shrine",
"ae": "3-3-1 Nagara-Naka, Kita-ku, Osaka"
},
{
"n": "富島神社",
"a": "大阪市北区中津2-5-10",
"s": "",
"r": "",
"k": "",
"d": "",
"c": "",
"m": "",
"ne": "Tomishima Shrine",
"ae": "2-5-10 Nakatsu, Kita-ku, Osaka"
},
{
"n": "大仁八阪神社",
"a": "大阪市北区大淀中3-1-23",
"s": "",
"r": "",
"k": "",
"d": "",
"c": "",
"m": "",
"ne": "Oni Yasaka Shrine",
"ae": "3-1-23 Oyodo-Naka, Kita-ku, Osaka"
},
{
"n": "素盞烏尊神社",
"a": "大阪市北区大淀南3-3-25",
"s": "",
"r": "",
"k": "",
"d": "",
"c": "",
"m": "",
"ne": "Susanoo-no-Mikoto Shrine",
"ae": "3-3-25 Oyodo-Minami, Kita-ku, Osaka"
},
{
"n": "淀川天神社",
"a": "大阪市北区国分寺1-4-1",
"s": "",
"r": "",
"k": "",
"d": "",
"c": "",
"m": "",
"ne": "Yodogawa Tenjin Shrine",
"ae": "1-4-1 Kokubunji, Kita-ku, Osaka"
},
{
"n": "南長柄八幡宮",
"a": "大阪市北区長柄中1-4-25",
"s": "",
"r": "",
"k": "",
"d": "",
"c": "",
"m": "",
"ne": "Minami-Nagara Hachimangu Shrine",
"ae": "1-4-25 Nagara-Naka, Kita-ku, Osaka"
},
{
"n": "野田恵美須神社",
"a": "大阪市福島区玉川4-1-1",
"s": "",
"r": "",
"k": "",
"d": "",
"c": "",
"m": "",
"ne": "Noda Ebisu Shrine",
"ae": "4-1-1 Tamagawa, Fukushima-ku, Osaka"
},
{
"n": "福島天満宮",
"a": "大阪市福島区福島2-8-1",
"s": "",
"r": "",
"k": "",
"d": "",
"c": "",
"m": "",
"ne": "Fukushima Tenmangu Shrine",
"ae": "2-8-1 Fukushima, Fukushima-ku, Osaka"
},
{
"n": "海老江八坂神社",
"a": "大阪市福島区海老江6-4-2",
"s": "",
"r": "",
"k": "",
"d": "",
"c": "",
"m": "",
"ne": "Ebie Yasaka Shrine",
"ae": "6-4-2 Ebie, Fukushima-ku, Osaka"
},
{
"n": "天神社",
"a": "大阪市福島区玉川1-4-5",
"s": "",
"r": "",
"k": "",
"d": "",
"c": "",
"m": "",
"ne": "Tenjin Shrine",
"ae": "1-4-5 Tamagawa, Fukushima-ku, Osaka"
},
{
"n": "春日神社",
"a": "大阪市福島区玉川2-2-7",
"s": "",
"r": "",
"k": "",
"d": "",
"c": "",
"m": "",
"ne": "Kasuga Shrine",
"ae": "2-2-7 Tamagawa, Fukushima-ku, Osaka"
},
{
"n": "神津神社",
"a": "大阪市淀川区十三東2-6-39",
"s": "",
"r": "",
"k": "",
"d": "",
"c": "",
"m": "",
"ne": "Kamitsu Shrine",
"ae": "2-6-39 Juso-Higashi, Yodogawa-ku, Osaka"
},
{
"n": "香具波志神社",
"a": "大阪市淀川区加島4-4-20",
"s": "",
"r": "",
"k": "",
"d": "",
"c": "",
"m": "",
"ne": "Kaguhashi Shrine",
"ae": "4-4-20 Kashima, Yodogawa-ku, Osaka"
},
{
"n": "蒲田神社",
"a": "大阪市淀川区東三国2-18-12",
"s": "",
"r": "",
"k": "",
"d": "",
"c": "",
"m": "",
"ne": "Kamata Shrine",
"ae": "2-18-12 Higashi-Mikuni, Yodogawa-ku, Osaka"
},
{
"n": "塚本神社",
"a": "大阪市淀川区塚本2-2-7",
"s": "",
"r": "",
"k": "",
"d": "",
"c": "",
"m": "",
"ne": "Tsukamoto Shrine",
"ae": "2-2-7 Tsukamoto, Yodogawa-ku, Osaka"
},
{
"n": "野里住吉神社",
"a": "大阪市西淀川区野里1-15-12",
"s": "",
"r": "",
"k": "",
"d": "",
"c": "1382年（永徳2年）",
"m": "住吉大神",
"ne": "Nozato Sumiyoshi Shrine",
"ae": "1-15-12 Nozato, Nishiyodogawa-ku, Osaka",
"ce": "1382 (Eitoku 2)",
"me": "Sumiyoshi-no-Okami"
},
{
"n": "田蓑神社",
"a": "大阪市西淀川区佃1-18-14",
"s": "",
"r": "",
"k": "",
"d": "",
"c": "869年（貞観3年）",
"m": "住吉四神",
"ne": "Tamino Shrine",
"ae": "1-18-14 Tsukuda, Nishiyodogawa-ku, Osaka",
"ce": "869 (Jogan 3)",
"me": "The four Sumiyoshi deities"
},
{
"n": "姫嶋神社",
"a": "大阪市西淀川区姫島4-14-2",
"s": "",
"r": "",
"k": "",
"d": "",
"c": "",
"m": "阿迦留姫命・住吉大神",
"ne": "Himejima Shrine",
"ae": "4-14-2 Himejima, Nishiyodogawa-ku, Osaka",
"me": "Akaruhime-no-Mikoto and Sumiyoshi-no-Okami"
},
{
"n": "大和田住吉神社",
"a": "大阪市西淀川区大和田5-20-20",
"s": "",
"r": "",
"k": "",
"d": "",
"c": "",
"m": "住吉四神",
"ne": "Owada Sumiyoshi Shrine",
"ae": "5-20-20 Owada, Nishiyodogawa-ku, Osaka",
"me": "The four Sumiyoshi deities"
},
{
"n": "鼻川神社",
"a": "大阪市西淀川区花川2-1-12",
"s": "",
"r": "",
"k": "",
"d": "",
"c": "",
"m": "神功皇后・須佐之男命",
"ne": "Hanakawa Shrine",
"ae": "2-1-12 Hanakawa, Nishiyodogawa-ku, Osaka",
"me": "Empress Jingu and Susanoo-no-Mikoto"
},
{
"n": "鼻川神社御旅所",
"a": "大阪市西淀川区柏里（番地は未確認）",
"s": "",
"r": "鼻川神社の行宮（御旅所）",
"k": "",
"d": "",
"c": "",
"m": "",
"ne": "Hanakawa Shrine Otabisho (procession rest site)",
"ae": "Kashiwazato, Nishiyodogawa-ku, Osaka (street number unconfirmed)",
"re": "Angu / Otabisho (temporary shrine) of {P}"
},
{
"n": "五社神社",
"a": "大阪市西淀川区中島1-2-8",
"s": "",
"r": "",
"k": "",
"d": "",
"c": "1688年（元禄元年）",
"m": "天照大御神・住吉大神・須佐之男命・豊受大神・火之迦具土神",
"ne": "Gosha Shrine",
"ae": "1-2-8 Nakajima, Nishiyodogawa-ku, Osaka",
"ce": "1688 (Genroku 1)",
"me": "Amaterasu-Omikami, Sumiyoshi-no-Okami, Susanoo-no-Mikoto, Toyouke-no-Okami and Hinokagutsuchi-no-Kami"
},
{
"n": "住吉神社",
"a": "大阪市西淀川区百島1-3-98",
"s": "",
"r": "",
"k": "",
"d": "",
"c": "1644年（正保元年）",
"m": "住吉四神",
"ne": "Sumiyoshi Shrine",
"ae": "1-3-98 Momojima, Nishiyodogawa-ku, Osaka",
"ce": "1644 (Shoho 1)",
"me": "The four Sumiyoshi deities"
},
{
"n": "櫻宮",
"a": "大阪市都島区中野町1-12-32",
"s": "",
"r": "",
"k": "",
"d": "",
"c": "",
"m": "",
"ne": "Sakuranomiya Shrine",
"ae": "1-12-32 Nakanocho, Miyakojima-ku, Osaka"
},
{
"n": "櫻宮御旅所",
"a": "大阪市都島区善源寺町（番地は未確認）",
"s": "",
"r": "櫻宮の行宮（御旅所）",
"k": "",
"d": "",
"c": "",
"m": "",
"ne": "Sakuranomiya Otabisho (procession rest site)",
"ae": "Zengenjicho, Miyakojima-ku, Osaka (street number unconfirmed)",
"re": "Angu / Otabisho (temporary shrine) of {P}"
},
{
"n": "都島神社",
"a": "大阪市都島区本通1-5-5",
"s": "",
"r": "",
"k": "",
"d": "",
"c": "",
"m": "",
"ne": "Miyakojima Shrine",
"ae": "1-5-5 Hondori, Miyakojima-ku, Osaka"
},
{
"n": "淀川神社",
"a": "大阪市都島区毛馬町1-2-11",
"s": "",
"r": "",
"k": "",
"d": "",
"c": "",
"m": "",
"ne": "Yodogawa Shrine",
"ae": "1-2-11 Kemacho, Miyakojima-ku, Osaka"
},
{
"n": "大宮神社",
"a": "大阪市旭区大宮3-1-37",
"s": "",
"r": "",
"k": "",
"d": "",
"c": "",
"m": "",
"ne": "Omiya Shrine",
"ae": "3-1-37 Omiya, Asahi-ku, Osaka"
},
{
"n": "八幡大神宮",
"a": "大阪市旭区清水3-20-19",
"s": "",
"r": "",
"k": "",
"d": "",
"c": "",
"m": "",
"ne": "Hachiman Daijingu Shrine",
"ae": "3-20-19 Shimizu, Asahi-ku, Osaka"
},
{
"n": "日吉神社",
"a": "大阪市旭区赤川4-19-13",
"s": "",
"r": "",
"k": "",
"d": "",
"c": "",
"m": "",
"ne": "Hiyoshi Shrine",
"ae": "4-19-13 Akagawa, Asahi-ku, Osaka"
},
{
"n": "八剱神社",
"a": "大阪市城東区鴫野東3-31-8",
"s": "",
"r": "",
"k": "",
"d": "",
"c": "",
"m": "",
"ne": "Yatsurugi Shrine",
"ae": "3-31-8 Shigino-Higashi, Joto-ku, Osaka"
},
{
"n": "皇大神宮",
"a": "大阪市城東区今福南2-12-31",
"s": "",
"r": "",
"k": "",
"d": "",
"c": "",
"m": "",
"ne": "Kotai Jingu Shrine",
"ae": "2-12-31 Imafuku-Minami, Joto-ku, Osaka"
},
{
"n": "皇大神宮行宮",
"a": "大阪市（所在地は未確認）",
"s": "",
"r": "皇大神宮の行宮（御旅所）",
"k": "",
"d": "",
"c": "",
"m": "",
"ne": "Kotai Jingu Shrine Angu (temporary shrine)",
"ae": "Osaka (location unconfirmed)",
"re": "Angu / Otabisho (temporary shrine) of {P}"
},
{
"n": "白山神社",
"a": "大阪市城東区中浜2-3-15",
"s": "",
"r": "",
"k": "",
"d": "",
"c": "",
"m": "",
"ne": "Hakusan Shrine",
"ae": "2-3-15 Nakahama, Joto-ku, Osaka"
},
{
"n": "野江水神社",
"a": "大阪市城東区野江4-1-39",
"s": "",
"r": "",
"k": "",
"d": "",
"c": "",
"m": "",
"ne": "Noe Sui Shrine",
"ae": "4-1-39 Noe, Joto-ku, Osaka"
},
{
"n": "須佐之男尊神社",
"a": "大阪市城東区成育5-15-20",
"s": "",
"r": "",
"k": "",
"d": "",
"c": "",
"m": "",
"ne": "Susanoo-no-Mikoto Shrine",
"ae": "5-15-20 Seiiku, Joto-ku, Osaka"
},
{
"n": "諏訪神社",
"a": "大阪市城東区諏訪2-15-16",
"s": "",
"r": "",
"k": "",
"d": "",
"c": "",
"m": "",
"ne": "Suwa Shrine",
"ae": "2-15-16 Suwa, Joto-ku, Osaka"
},
{
"n": "若宮八幡大神宮",
"a": "大阪市城東区蒲生4-3-16",
"s": "",
"r": "",
"k": "",
"d": "",
"c": "",
"m": "",
"ne": "Wakamiya Hachiman Daijingu Shrine",
"ae": "4-3-16 Gamo, Joto-ku, Osaka"
},
{
"n": "稲荷神社",
"a": "大阪市城東区中浜3-18-11",
"s": "",
"r": "",
"k": "",
"d": "",
"c": "",
"m": "",
"ne": "Inari Shrine",
"ae": "3-18-11 Nakahama, Joto-ku, Osaka"
},
{
"n": "鶴見神社",
"a": "大阪市鶴見区鶴見3-13-76",
"s": "",
"r": "",
"k": "",
"d": "",
"c": "",
"m": "",
"ne": "Tsurumi Shrine",
"ae": "3-13-76 Tsurumi, Tsurumi-ku, Osaka"
},
{
"n": "阿遅速雄神社",
"a": "大阪市鶴見区放出東3-31-18",
"s": "式内社",
"r": "",
"k": "",
"d": "",
"c": "",
"m": "",
"ne": "Ajihayao Shrine",
"ae": "3-31-18 Hanaten-Higashi, Tsurumi-ku, Osaka",
"se": "Shikinai-sha (Engishiki-listed)"
},
{
"n": "比枝神社",
"a": "大阪市鶴見区今津中5-5-23",
"s": "",
"r": "",
"k": "",
"d": "",
"c": "",
"m": "",
"ne": "Hie Shrine",
"ae": "5-5-23 Imazu-Naka, Tsurumi-ku, Osaka"
},
{
"n": "八幡神社",
"a": "大阪市鶴見区諸口2-4-41",
"s": "",
"r": "",
"k": "",
"d": "",
"c": "",
"m": "",
"ne": "Hachiman Shrine",
"ae": "2-4-41 Morokuchi, Tsurumi-ku, Osaka"
},
{
"n": "八幡宮",
"a": "大阪市鶴見区横堤2-8-25",
"s": "",
"r": "",
"k": "",
"d": "",
"c": "",
"m": "",
"ne": "Hachimangu Shrine",
"ae": "2-8-25 Yokozutsumi, Tsurumi-ku, Osaka"
},
{
"n": "大神社",
"a": "大阪市鶴見区茨田大宮1-18-17",
"s": "",
"r": "",
"k": "",
"d": "",
"c": "",
"m": "",
"ne": "Okami Shrine",
"ae": "1-18-17 Mattada-Omiya, Tsurumi-ku, Osaka"
},
{
"n": "古宮神社",
"a": "大阪市鶴見区浜4-16-20",
"s": "",
"r": "",
"k": "",
"d": "",
"c": "",
"m": "",
"ne": "Furumiya Shrine",
"ae": "4-16-20 Hama, Tsurumi-ku, Osaka"
},
{
"n": "大隅神社",
"a": "大阪市東淀川区大桐5-14-81",
"s": "",
"r": "",
"k": "",
"d": "",
"c": "",
"m": "",
"ne": "Osumi Shrine",
"ae": "5-14-81 Ogiri, Higashiyodogawa-ku, Osaka"
},
{
"n": "大隅神社御旅所",
"a": "大阪市東淀川区井高野（番地は未確認）",
"s": "",
"r": "大隅神社の行宮（御旅所）",
"k": "",
"d": "",
"c": "",
"m": "",
"ne": "Osumi Shrine Otabisho (procession rest site)",
"ae": "Itakano, Higashiyodogawa-ku, Osaka (street number unconfirmed)",
"re": "Angu / Otabisho (temporary shrine) of {P}"
},
{
"n": "大宮",
"a": "大阪市東淀川区大道南3-2-2",
"s": "",
"r": "",
"k": "",
"d": "",
"c": "",
"m": "",
"ne": "Omiya Shrine",
"ae": "3-2-2 Daido-Minami, Higashiyodogawa-ku, Osaka"
},
{
"n": "菅原天満宮",
"a": "大阪市東淀川区菅原2-3-27",
"s": "",
"r": "",
"k": "",
"d": "",
"c": "",
"m": "",
"ne": "Sugawara Tenmangu Shrine",
"ae": "2-3-27 Sugawara, Higashiyodogawa-ku, Osaka"
},
{
"n": "松山神社",
"a": "大阪市東淀川区小松4-15-38",
"s": "",
"r": "",
"k": "",
"d": "",
"c": "",
"m": "",
"ne": "Matsuyama Shrine",
"ae": "4-15-38 Komatsu, Higashiyodogawa-ku, Osaka"
},
{
"n": "春日神社",
"a": "大阪市東淀川区上新庄2-20-15",
"s": "",
"r": "",
"k": "",
"d": "",
"c": "",
"m": "",
"ne": "Kasuga Shrine",
"ae": "2-20-15 Kami-Shinjo, Higashiyodogawa-ku, Osaka"
},
{
"n": "柴島神社",
"a": "大阪市東淀川区柴島3-7-30",
"s": "",
"r": "",
"k": "",
"d": "",
"c": "",
"m": "",
"ne": "Kunijima Shrine",
"ae": "3-7-30 Kunijima, Higashiyodogawa-ku, Osaka"
},
{
"n": "中島惣社",
"a": "大阪市東淀川区東中島4-9-41",
"s": "",
"r": "",
"k": "",
"d": "",
"c": "",
"m": "",
"ne": "Nakajima Sosha Shrine",
"ae": "4-9-41 Higashi-Nakajima, Higashiyodogawa-ku, Osaka"
},
{
"n": "生國魂神社",
"a": "大阪市天王寺区生玉町13-9",
"s": "式内社（名神大）",
"r": "",
"k": "",
"d": "",
"c": "",
"m": "",
"ne": "Ikukunitama Shrine",
"ae": "13-9 Ikutamacho, Tennoji-ku, Osaka",
"se": "Shikinai-sha (Engishiki-listed) · Myojin Taisha"
},
{
"n": "久保神社",
"a": "大阪市天王寺区勝山2-5-14",
"s": "",
"r": "",
"k": "",
"d": "",
"c": "",
"m": "",
"ne": "Kubo Shrine",
"ae": "2-5-14 Katsuyama, Tennoji-ku, Osaka"
},
{
"n": "大江神社",
"a": "大阪市天王寺区夕陽丘町5-40",
"s": "",
"r": "",
"k": "",
"d": "",
"c": "",
"m": "",
"ne": "Oe Shrine",
"ae": "5-40 Yuhigaokacho, Tennoji-ku, Osaka"
},
{
"n": "上之宮址",
"a": "大阪市天王寺区（所在地は未確認）",
"s": "",
"r": "大江神社に合祀された上之宮神社の旧社地",
"k": "史跡（旧社地）",
"d": "",
"c": "",
"m": "",
"ne": "Site of Uenomiya Shrine",
"ae": "Tennoji-ku, Osaka (location unconfirmed)",
"re": "Former site of Uenomiya Shrine, now enshrined in {P}",
"ke": "Historic site (former shrine site)"
},
{
"n": "河堀稲生神社",
"a": "大阪市天王寺区大道3-7-3",
"s": "",
"r": "",
"k": "",
"d": "",
"c": "",
"m": "",
"ne": "Kobore Inari Shrine",
"ae": "3-7-3 Daido, Tennoji-ku, Osaka"
},
{
"n": "東高津宮",
"a": "大阪市天王寺区東高津町4-8",
"s": "",
"r": "",
"k": "",
"d": "",
"c": "",
"m": "",
"ne": "Higashi-Kozu-gu Shrine",
"ae": "4-8 Higashi-Kozucho, Tennoji-ku, Osaka"
},
{
"n": "安井神社",
"a": "大阪市天王寺区逢阪1-3-24",
"s": "",
"r": "",
"k": "",
"d": "",
"c": "",
"m": "",
"ne": "Yasui Shrine",
"ae": "1-3-24 Osaka, Tennoji-ku, Osaka"
},
{
"n": "五條宮",
"a": "大阪市天王寺区真法院町24-9",
"s": "",
"r": "",
"k": "",
"d": "",
"c": "",
"m": "",
"ne": "Gojo-no-miya Shrine",
"ae": "24-9 Shinpoincho, Tennoji-ku, Osaka"
},
{
"n": "三光神社",
"a": "大阪市天王寺区玉造本町14-90",
"s": "",
"r": "",
"k": "",
"d": "",
"c": "",
"m": "",
"ne": "Sanko Shrine",
"ae": "14-90 Tamatsukuri-Honmachi, Tennoji-ku, Osaka"
},
{
"n": "堀越神社",
"a": "大阪市天王寺区茶臼山町1-8",
"s": "",
"r": "",
"k": "",
"d": "",
"c": "",
"m": "",
"ne": "Horikoshi Shrine",
"ae": "1-8 Chausuyamacho, Tennoji-ku, Osaka"
},
{
"n": "清見原神社",
"a": "大阪市生野区小路2-24-35",
"s": "",
"r": "",
"k": "",
"d": "",
"c": "",
"m": "",
"ne": "Kiyomihara Shrine",
"ae": "2-24-35 Shoji, Ikuno-ku, Osaka"
},
{
"n": "巽神社",
"a": "大阪市生野区巽南3-17-19",
"s": "",
"r": "",
"k": "",
"d": "",
"c": "",
"m": "",
"ne": "Tatsumi Shrine",
"ae": "3-17-19 Tatsumi-Minami, Ikuno-ku, Osaka"
},
{
"n": "横野神社跡",
"a": "大阪市生野区巽西3-9",
"s": "",
"r": "巽神社に合祀された式内社の旧社地",
"k": "史跡（旧社地）",
"d": "",
"c": "",
"m": "印色入日子命",
"ne": "Site of Yokono Shrine",
"ae": "3-9 Tatsumi-Nishi, Ikuno-ku, Osaka",
"re": "Former site of a Shikinai-sha, now enshrined in {P}",
"ke": "Historic site (former shrine site)",
"me": "Inishikiirihiko-no-Mikoto"
},
{
"n": "御幸森天神宮",
"a": "大阪市生野区桃谷3-10-5",
"s": "",
"r": "",
"k": "",
"d": "",
"c": "",
"m": "",
"ne": "Miyukimori Tenjingu Shrine",
"ae": "3-10-5 Momodani, Ikuno-ku, Osaka"
},
{
"n": "田島神社",
"a": "大阪市生野区田島3-5-34",
"s": "",
"r": "",
"k": "",
"d": "",
"c": "",
"m": "",
"ne": "Tajima Shrine",
"ae": "3-5-34 Tajima, Ikuno-ku, Osaka"
},
{
"n": "生野神社",
"a": "大阪市生野区舎利寺1-2-27",
"s": "",
"r": "",
"k": "",
"d": "",
"c": "",
"m": "",
"ne": "Ikuno Shrine",
"ae": "1-2-27 Shariji, Ikuno-ku, Osaka"
},
{
"n": "生野八坂神社",
"a": "大阪市生野区生野東4-7-11",
"s": "",
"r": "",
"k": "",
"d": "",
"c": "",
"m": "",
"ne": "Ikuno Yasaka Shrine",
"ae": "4-7-11 Ikuno-Higashi, Ikuno-ku, Osaka"
},
{
"n": "彌栄神社",
"a": "大阪市生野区桃谷2-16-22",
"s": "",
"r": "",
"k": "",
"d": "",
"c": "",
"m": "",
"ne": "Iyasaka Shrine",
"ae": "2-16-22 Momodani, Ikuno-ku, Osaka"
},
{
"n": "今宮戎神社",
"a": "大阪市浪速区恵美須西1-6-10",
"s": "",
"r": "",
"k": "",
"d": "",
"c": "",
"m": "",
"ne": "Imamiya Ebisu Shrine",
"ae": "1-6-10 Ebisu-Nishi, Naniwa-ku, Osaka"
},
{
"n": "難波八阪神社",
"a": "大阪市浪速区元町2-9-19",
"s": "",
"r": "",
"k": "",
"d": "",
"c": "",
"m": "",
"ne": "Namba Yasaka Shrine",
"ae": "2-9-19 Motomachi, Naniwa-ku, Osaka"
},
{
"n": "浪速神社",
"a": "大阪市浪速区浪速西3-10-23",
"s": "",
"r": "坐摩神社の境外末社",
"k": "",
"d": "",
"c": "",
"m": "坐摩大神・猿田彦大神",
"ne": "Naniwa Shrine",
"ae": "3-10-23 Naniwa-Nishi, Naniwa-ku, Osaka",
"re": "Off-site auxiliary shrine of {P}",
"me": "Ikasuri-no-Okami and Sarutahiko-no-Okami"
},
{
"n": "敷津松之宮",
"a": "大阪市浪速区敷津西1-2-12",
"s": "",
"r": "",
"k": "",
"d": "",
"c": "",
"m": "",
"ne": "Shikitsu Matsunomiya Shrine",
"ae": "1-2-12 Shikitsu-Nishi, Naniwa-ku, Osaka"
},
{
"n": "敷津松之宮西成旅所",
"a": "大阪市西成区松（番地は未確認）",
"s": "",
"r": "敷津松之宮の行宮（御旅所）",
"k": "",
"d": "",
"c": "",
"m": "",
"ne": "Shikitsu Matsunomiya Nishinari Tabisho (procession rest site)",
"ae": "Matsu, Nishinari-ku, Osaka (street number unconfirmed)",
"re": "Angu / Otabisho (temporary shrine) of {P}"
},
{
"n": "廣田神社",
"a": "大阪市浪速区日本橋西2-4-14",
"s": "",
"r": "",
"k": "",
"d": "",
"c": "",
"m": "",
"ne": "Hirota Shrine",
"ae": "2-4-14 Nipponbashi-Nishi, Naniwa-ku, Osaka"
},
{
"n": "赤手拭稲荷神社",
"a": "大阪市浪速区稲荷2-6-26",
"s": "",
"r": "",
"k": "",
"d": "",
"c": "",
"m": "",
"ne": "Akatenugui Inari Shrine",
"ae": "2-6-26 Inari, Naniwa-ku, Osaka"
},
{
"n": "生根神社",
"a": "大阪市西成区玉出西2-1-10",
"s": "",
"r": "",
"k": "",
"d": "",
"c": "",
"m": "",
"ne": "Ikune Shrine",
"ae": "2-1-10 Tamade-Nishi, Nishinari-ku, Osaka"
},
{
"n": "天神ノ森天満宮",
"a": "大阪市西成区岸里東2-3-19",
"s": "",
"r": "",
"k": "",
"d": "",
"c": "",
"m": "",
"ne": "Tenjin-no-Mori Tenmangu Shrine",
"ae": "2-3-19 Kishinosato-Higashi, Nishinari-ku, Osaka"
},
{
"n": "津守神社",
"a": "大阪市西成区津守3-4-1",
"s": "",
"r": "",
"k": "",
"d": "",
"c": "",
"m": "",
"ne": "Tsumori Shrine",
"ae": "3-4-1 Tsumori, Nishinari-ku, Osaka"
},
{
"n": "泉尾神社",
"a": "大阪市大正区泉尾2-17-8",
"s": "",
"r": "",
"k": "",
"d": "",
"c": "",
"m": "",
"ne": "Izuo Shrine",
"ae": "2-17-8 Izuo, Taisho-ku, Osaka"
},
{
"n": "八阪神社",
"a": "大阪市大正区三軒家東6-14-12",
"s": "",
"r": "",
"k": "",
"d": "",
"c": "",
"m": "",
"ne": "Yasaka Shrine",
"ae": "6-14-12 Sangenya-Higashi, Taisho-ku, Osaka"
},
{
"n": "八坂神社",
"a": "大阪市大正区三軒家東2-7-18",
"s": "",
"r": "",
"k": "",
"d": "",
"c": "",
"m": "",
"ne": "Yasaka Shrine",
"ae": "2-7-18 Sangenya-Higashi, Taisho-ku, Osaka"
},
{
"n": "南恩加島天満宮",
"a": "大阪市大正区小林西1-7-13",
"s": "",
"r": "",
"k": "",
"d": "",
"c": "",
"m": "",
"ne": "Minami-Onkajima Tenmangu Shrine",
"ae": "1-7-13 Kobayashi-Nishi, Taisho-ku, Osaka"
},
{
"n": "産土神社",
"a": "大阪市大正区小林西1-7-13",
"s": "",
"r": "",
"k": "",
"d": "",
"c": "",
"m": "",
"ne": "Ubusuna Shrine",
"ae": "1-7-13 Kobayashi-Nishi, Taisho-ku, Osaka"
},
{
"n": "神明神社",
"a": "大阪市大正区鶴町2-7-29",
"s": "",
"r": "",
"k": "",
"d": "",
"c": "",
"m": "",
"ne": "Shinmei Shrine",
"ae": "2-7-29 Tsurumachi, Taisho-ku, Osaka"
},
{
"n": "阿倍王子神社",
"a": "大阪市阿倍野区阿倍野元町9-4",
"s": "",
"r": "",
"k": "",
"d": "",
"c": "",
"m": "",
"ne": "Abeoji Shrine",
"ae": "9-4 Abeno-Motomachi, Abeno-ku, Osaka"
},
{
"n": "阿倍晴明神社",
"a": "大阪市阿倍野区阿倍野元町5-16",
"s": "",
"r": "阿倍王子神社の末社",
"k": "",
"d": "",
"c": "",
"m": "安倍晴明",
"ne": "Abe-no-Seimei Shrine",
"ae": "5-16 Abeno-Motomachi, Abeno-ku, Osaka",
"re": "Auxiliary shrine of {P}",
"me": "Abe no Seimei"
},
{
"n": "阿倍野神社",
"a": "大阪市阿倍野区北畠3-7-20",
"s": "",
"r": "",
"k": "",
"d": "",
"c": "",
"m": "",
"ne": "Abeno Shrine",
"ae": "3-7-20 Kitabatake, Abeno-ku, Osaka"
},
{
"n": "杭全神社",
"a": "大阪市平野区平野宮町2-1-67",
"s": "",
"r": "",
"k": "",
"d": "",
"c": "862年（貞観4年）",
"m": "",
"ne": "Kumata Shrine",
"ae": "2-1-67 Hirano-Miyamachi, Hirano-ku, Osaka",
"ce": "862 (Jogan 4)"
},
{
"n": "赤留比売命神社",
"a": "大阪市平野区平野東2-11",
"s": "式内社",
"r": "杭全神社の境外末社（かつては住吉大社の末社）",
"k": "",
"d": "",
"c": "",
"m": "赤留比売命",
"ne": "Akaruhime-no-Mikoto Shrine",
"ae": "2-11 Hirano-Higashi, Hirano-ku, Osaka",
"se": "Shikinai-sha (Engishiki-listed)",
"re": "Off-site auxiliary shrine of {P} (formerly an auxiliary shrine of Sumiyoshi Taisha)",
"me": "Akaruhime-no-Mikoto"
},
{
"n": "旭神社",
"a": "大阪市平野区加美正覚寺1-17-30",
"s": "",
"r": "",
"k": "",
"d": "",
"c": "",
"m": "",
"ne": "Asahi Shrine",
"ae": "1-17-30 Kami-Shokakuji, Hirano-ku, Osaka"
},
{
"n": "志紀長吉神社",
"a": "大阪市平野区長吉長原2-8-23",
"s": "式内社（大社）",
"r": "",
"k": "",
"d": "",
"c": "",
"m": "",
"ne": "Shiki Nagayoshi Shrine",
"ae": "2-8-23 Nagayoshi-Nagahara, Hirano-ku, Osaka",
"se": "Shikinai-sha (Engishiki-listed) · Grand Shrine"
},
{
"n": "菅原神社",
"a": "大阪市平野区加美鞍作1-5-17",
"s": "",
"r": "",
"k": "",
"d": "",
"c": "",
"m": "",
"ne": "Sugawara Shrine",
"ae": "1-5-17 Kami-Kurazukuri, Hirano-ku, Osaka"
},
{
"n": "瓜破天神社",
"a": "大阪市平野区瓜破5-4-19",
"s": "",
"r": "",
"k": "",
"d": "",
"c": "",
"m": "",
"ne": "Uriwari Tenjin Shrine",
"ae": "5-4-19 Uriwari, Hirano-ku, Osaka"
},
{
"n": "産土神社",
"a": "大阪市平野区長吉出戸6-10-14",
"s": "",
"r": "",
"k": "",
"d": "",
"c": "",
"m": "",
"ne": "Ubusuna Shrine",
"ae": "6-10-14 Nagayoshi-Deto, Hirano-ku, Osaka"
},
{
"n": "川辺八幡神社",
"a": "大阪市平野区長吉川辺1-4-38",
"s": "",
"r": "",
"k": "",
"d": "",
"c": "",
"m": "",
"ne": "Kawabe Hachiman Shrine",
"ae": "1-4-38 Nagayoshi-Kawabe, Hirano-ku, Osaka"
},
{
"n": "天照皇大神社",
"a": "大阪市平野区長吉出戸4-4-318",
"s": "",
"r": "",
"k": "",
"d": "",
"c": "",
"m": "",
"ne": "Amaterasu Kotai Shrine",
"ae": "4-4-318 Nagayoshi-Deto, Hirano-ku, Osaka"
},
{
"n": "赤坂神社",
"a": "大阪市平野区長吉六反1-14-24",
"s": "",
"r": "",
"k": "",
"d": "",
"c": "",
"m": "",
"ne": "Akasaka Shrine",
"ae": "1-14-24 Nagayoshi-Rokutan, Hirano-ku, Osaka"
},
{
"n": "新家天満宮",
"a": "大阪市平野区加美南5-3-25",
"s": "",
"r": "",
"k": "",
"d": "",
"c": "",
"m": "",
"ne": "Shinya Tenmangu Shrine",
"ae": "5-3-25 Kami-Minami, Hirano-ku, Osaka"
},
{
"n": "式内楯原神社",
"a": "大阪市平野区喜連6-1-38",
"s": "式内社",
"r": "",
"k": "",
"d": "",
"c": "",
"m": "",
"ne": "Shikinai Tatehara Shrine",
"ae": "6-1-38 Kire, Hirano-ku, Osaka",
"se": "Shikinai-sha (Engishiki-listed)"
},
{
"n": "八坂神社",
"a": "大阪市平野区喜連東2-1-21",
"s": "",
"r": "",
"k": "",
"d": "",
"c": "",
"m": "",
"ne": "Yasaka Shrine",
"ae": "2-1-21 Kire-Higashi, Hirano-ku, Osaka"
},
{
"n": "山阪神社",
"a": "大阪市東住吉区山坂2-19-23",
"s": "国史見在社",
"r": "",
"k": "",
"d": "",
"c": "",
"m": "",
"ne": "Yamasaka Shrine",
"ae": "2-19-23 Yamasaka, Higashisumiyoshi-ku, Osaka",
"se": "Kokushi-kenzaisha (named in the Six National Histories)"
},
{
"n": "桑津天神社",
"a": "大阪市東住吉区桑津3-4-17",
"s": "",
"r": "",
"k": "",
"d": "",
"c": "",
"m": "",
"ne": "Kuwazu Tenjin Shrine",
"ae": "3-4-17 Kuwazu, Higashisumiyoshi-ku, Osaka"
},
{
"n": "阿麻美許曽神社",
"a": "大阪市東住吉区矢田7-6-18",
"s": "式内社",
"r": "",
"k": "",
"d": "",
"c": "",
"m": "",
"ne": "Amamikoso Shrine",
"ae": "7-6-18 Yada, Higashisumiyoshi-ku, Osaka",
"se": "Shikinai-sha (Engishiki-listed)"
},
{
"n": "素盞嗚尊神社",
"a": "大阪市東住吉区鷹合4-5-22",
"s": "",
"r": "",
"k": "",
"d": "",
"c": "",
"m": "",
"ne": "Susanoo-no-Mikoto Shrine",
"ae": "4-5-22 Takaai, Higashisumiyoshi-ku, Osaka"
},
{
"n": "湯里住吉神社",
"a": "大阪市東住吉区湯里4-17-14",
"s": "",
"r": "",
"k": "",
"d": "",
"c": "",
"m": "",
"ne": "Yuzato Sumiyoshi Shrine",
"ae": "4-17-14 Yuzato, Higashisumiyoshi-ku, Osaka"
},
{
"n": "中臣須牟地神社",
"a": "大阪市東住吉区住道矢田2-9-20",
"s": "式内社（大社）",
"r": "",
"k": "",
"d": "",
"c": "",
"m": "",
"ne": "Nakatomi Sumuchi Shrine",
"ae": "2-9-20 Suminodo-Yada, Higashisumiyoshi-ku, Osaka",
"se": "Shikinai-sha (Engishiki-listed) · Grand Shrine"
},
{
"n": "榎神社",
"a": "大阪市東住吉区北田辺1-9-20",
"s": "",
"r": "",
"k": "",
"d": "",
"c": "",
"m": "",
"ne": "Enoki Shrine",
"ae": "1-9-20 Kita-Tanabe, Higashisumiyoshi-ku, Osaka"
},
{
"n": "中井神社",
"a": "大阪市東住吉区針中野2-3-58",
"s": "国史見在社",
"r": "",
"k": "",
"d": "",
"c": "",
"m": "",
"ne": "Nakai Shrine",
"ae": "2-3-58 Harinakano, Higashisumiyoshi-ku, Osaka",
"se": "Kokushi-kenzaisha (named in the Six National Histories)"
},
{
"n": "住吉大社",
"a": "大阪市住吉区住吉2-9-89",
"s": "式内社（名神大）",
"r": "",
"k": "",
"d": "",
"c": "",
"m": "住吉三神（底筒男命・中筒男命・表筒男命）と神功皇后",
"ne": "Sumiyoshi Taisha",
"ae": "2-9-89 Sumiyoshi, Sumiyoshi-ku, Osaka",
"se": "Shikinai-sha (Engishiki-listed) · Myojin Taisha",
"me": "The three Sumiyoshi deities (Sokotsutsu-no-O, Nakatsutsu-no-O and Uwatsutsu-no-O) and Empress Jingu"
},
{
"n": "宿院頓宮",
"a": "堺市堺区宿院町東2-1-6",
"s": "",
"r": "住吉大社の行宮（御旅所）",
"k": "",
"d": "",
"c": "",
"m": "",
"ne": "Shukuin Tongu (temporary shrine of Sumiyoshi Taisha)",
"ae": "2-1-6 Shukuincho-Higashi, Sakai-ku, Sakai City",
"re": "Angu / Otabisho (temporary shrine) of {P}"
},
{
"n": "大海神社",
"a": "大阪市住吉区住吉2-9-89",
"s": "式内社",
"r": "住吉大社の摂社",
"k": "",
"d": "",
"c": "",
"m": "豊玉彦命・豊玉姫命",
"ne": "Oama Shrine",
"ae": "2-9-89 Sumiyoshi, Sumiyoshi-ku, Osaka",
"se": "Shikinai-sha (Engishiki-listed)",
"re": "Subsidiary shrine (Sessha) of {P}",
"me": "Toyotamahiko-no-Mikoto and Toyotamahime-no-Mikoto"
},
{
"n": "生根神社",
"a": "大阪市住吉区住吉2-3-15",
"s": "式内社（大社）",
"r": "",
"k": "",
"d": "",
"c": "",
"m": "",
"ne": "Ikune Shrine",
"ae": "2-3-15 Sumiyoshi, Sumiyoshi-ku, Osaka",
"se": "Shikinai-sha (Engishiki-listed) · Grand Shrine"
},
{
"n": "止止呂支比賣命神社",
"a": "大阪市住吉区沢之町1-10-4",
"s": "式内社",
"r": "",
"k": "",
"d": "",
"c": "",
"m": "",
"ne": "Todorokihime-no-Mikoto Shrine",
"ae": "1-10-4 Sawanocho, Sumiyoshi-ku, Osaka",
"se": "Shikinai-sha (Engishiki-listed)"
},
{
"n": "天水分豊浦命神社",
"a": "大阪市住吉区沢之町1-10-4",
"s": "式内社",
"r": "止止呂支比賣命神社の境内社",
"k": "",
"d": "",
"c": "",
"m": "天水分神・奥津彦神・奥津姫神",
"ne": "Amenomikumaritoyura-no-Mikoto Shrine",
"ae": "1-10-4 Sawanocho, Sumiyoshi-ku, Osaka",
"se": "Shikinai-sha (Engishiki-listed)",
"re": "Shrine within the precincts of {P}",
"me": "Ame-no-Mikumari-no-Kami, Okitsuhiko-no-Kami and Okitsuhime-no-Kami"
},
{
"n": "霰松原神社",
"a": "大阪市住之江区安立2-11",
"s": "",
"r": "止止呂支比賣命神社に合祀された式内社（天水分豊浦命神社）の旧社地",
"k": "史跡（旧社地）",
"d": "",
"c": "",
"m": "霰松原荒神",
"ne": "Arare-matsubara Shrine",
"ae": "2-11 Anryu, Suminoe-ku, Osaka",
"re": "Former site of Amenomikumaritoyura-no-Mikoto Shrine (Shikinai-sha), now enshrined in {P}",
"ke": "Historic site (former shrine site)",
"me": "Arare-matsubara Kojin"
},
{
"n": "神須牟地神社",
"a": "大阪市住吉区長居西2-1-4",
"s": "式内社",
"r": "",
"k": "",
"d": "",
"c": "",
"m": "",
"ne": "Kamisumuchi Shrine",
"ae": "2-1-4 Nagai-Nishi, Sumiyoshi-ku, Osaka",
"se": "Shikinai-sha (Engishiki-listed)"
},
{
"n": "多米神社跡",
"a": "大阪市住吉区長居2-8-1",
"s": "",
"r": "神須牟地神社に合祀された式内社の旧社地",
"k": "史跡（旧社地）",
"d": "",
"c": "",
"m": "",
"ne": "Site of Tame Shrine",
"ae": "2-8-1 Nagai, Sumiyoshi-ku, Osaka",
"re": "Former site of a Shikinai-sha, now enshrined in {P}",
"ke": "Historic site (former shrine site)"
},
{
"n": "保利神社",
"a": "大阪市住吉区長居東1-14-17",
"s": "",
"r": "",
"k": "",
"d": "",
"c": "",
"m": "",
"ne": "Hori Shrine",
"ae": "1-14-17 Nagai-Higashi, Sumiyoshi-ku, Osaka"
},
{
"n": "大依羅神社",
"a": "大阪市住吉区庭井2-18-16",
"s": "式内社（名神大）",
"r": "",
"k": "",
"d": "",
"c": "",
"m": "",
"ne": "Oyosami Shrine",
"ae": "2-18-16 Niwai, Sumiyoshi-ku, Osaka",
"se": "Shikinai-sha (Engishiki-listed) · Myojin Taisha"
},
{
"n": "努能太比売命神社跡",
"a": "大阪市住吉区杉本2-17",
"s": "",
"r": "大依羅神社に合祀された式内社の旧社地",
"k": "史跡（旧社地）",
"d": "",
"c": "",
"m": "",
"ne": "Site of Nunotahime-no-Mikoto Shrine",
"ae": "2-17 Sugimoto, Sumiyoshi-ku, Osaka",
"re": "Former site of a Shikinai-sha, now enshrined in {P}",
"ke": "Historic site (former shrine site)"
},
{
"n": "草津大歳社跡",
"a": "大阪市住吉区苅田6-10-12",
"s": "",
"r": "大依羅神社に合祀された式内社の旧社地",
"k": "史跡（旧社地）",
"d": "",
"c": "",
"m": "",
"ne": "Site of Kusatsu Otoshi Shrine",
"ae": "6-10-12 Karita, Sumiyoshi-ku, Osaka",
"re": "Former site of a Shikinai-sha, now enshrined in {P}",
"ke": "Historic site (former shrine site)"
},
{
"n": "大阪護國神社",
"a": "大阪市住之江区南加賀屋1-1-77",
"s": "",
"r": "",
"k": "",
"d": "",
"c": "",
"m": "",
"ne": "Osaka Gokoku Shrine",
"ae": "1-1-77 Minami-Kagaya, Suminoe-ku, Osaka"
},
{
"n": "高崎神社",
"a": "大阪市住之江区南加賀屋4-15-3",
"s": "",
"r": "",
"k": "",
"d": "",
"c": "",
"m": "",
"ne": "Takasaki Shrine",
"ae": "4-15-3 Minami-Kagaya, Suminoe-ku, Osaka"
},
{
"n": "加賀屋天満宮",
"a": "大阪市住之江区北加賀屋5-2-4",
"s": "",
"r": "",
"k": "",
"d": "",
"c": "",
"m": "",
"ne": "Kagaya Tenmangu Shrine",
"ae": "5-2-4 Kita-Kagaya, Suminoe-ku, Osaka"
},
{
"n": "高砂神社",
"a": "大阪市住之江区北島3-14-12",
"s": "",
"r": "",
"k": "",
"d": "",
"c": "",
"m": "",
"ne": "Takasago Shrine",
"ae": "3-14-12 Kitajima, Suminoe-ku, Osaka"
}
];
var WARD_EN = {"中央区": "Chuo-ku", "西区": "Nishi-ku", "東成区": "Higashinari-ku", "港区": "Minato-ku", "此花区": "Konohana-ku", "北区": "Kita-ku", "福島区": "Fukushima-ku", "淀川区": "Yodogawa-ku", "西淀川区": "Nishiyodogawa-ku", "都島区": "Miyakojima-ku", "旭区": "Asahi-ku", "城東区": "Joto-ku", "鶴見区": "Tsurumi-ku", "東淀川区": "Higashiyodogawa-ku", "天王寺区": "Tennoji-ku", "生野区": "Ikuno-ku", "浪速区": "Naniwa-ku", "西成区": "Nishinari-ku", "大正区": "Taisho-ku", "阿倍野区": "Abeno-ku", "平野区": "Hirano-ku", "東住吉区": "Higashisumiyoshi-ku", "住吉区": "Sumiyoshi-ku", "住之江区": "Suminoe-ku", "堺市堺区": "Sakai-ku, Sakai City", "所在地未確認": "Location unconfirmed"};
